development:
  adapter: postgresql
  encoding: unicode
  database: depot_application
  host: localhost
  pool: 5
  username: postgres
  password: ENV["POSTGRES_SECRET"]

test:
  adapter: postgresql
  encoding: unicode
  database: test_db
  pool: 5
  username: katenorquay
  password: ENV["POSTGRES_PASSWORD"]

production:
  adapter: postgresql
  encoding: unicode
  database: depot_application
  pool: 5
  username: postgres
  password: ENV["POSTGRES_SECRET"]
