development:
  adapter: postgresql
  encoding: unicode
  database: depot_application
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: depot_application
  pool: 5
  username: postgres
  password: postgres
